### ISSUE TITLE
"Runtime error processing wasm" when using std::to_string

### ISSUE THREAD

**Issue by sim31** [EOSIO/eosio.wasmsdk#58]
I'm not sure if I should post this in eosio repo or here, but since I don't see this issue when compiling with the old eosiocpp, I decided to post here.

This modified hello example program reproduces the issue for me:
```
#include <eosiolib/eosio.hpp>
#include <string>

using namespace eosio;
class hello : public eosio::contract {
  public:
      using contract::contract;

      /// @abi action 
      void hi( account_name user, uint64_t i ) {
         std::string str = std::to_string(i);
         print( "Hello, ", name{user});
      }
};

EOSIO_ABI( hello, (hi) )

```
It compiles fine with this command:
```
eosio-cpp -o hello.wasm hello.cpp
```
Sending this action fails and produces this error in the nodeos log:
```
2018-08-28T15:00:23.226 thread-0   http_plugin.cpp:476           handle_exception     ] Exception Details: 3070002 wasm_execution_error: Runtime Error Processing WASM
final > memory: 18446744073709551520 > 65536
    {}
    thread-0  binaryen.hpp:76 trap
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one
```

Like I already said, compiling the old way, with eosiocpp does not produce this error. And if I don't call std::to_string it works fine as well. So something happens in std::to_string.

Would be good, if someone tried to reproduce. I didn't run the standard build.sh script, to build, because my OS is not supported (Arch linux).

I'm running eosio.wasmsdk v1.1.1 and eosio v1.1.6.

**Comment by larryk85** [comment]
The size explosion from adding std::to_string is expected.  Pulling in standard library functions in general will add a lot to a contract, especially the string manipulation/handling functions.  I don't know why you were going to use to_string in your contract, but as a general design choice you should not be doing any string manipulations, they are very expensive.  As for the reference to the old toolchain, when I compiled this it was smaller because it wasn't linking parts that it needs to function correctly, at least it failed when I actually used that variable.

**Comment by sim31** [comment]
So that error says that wasm is too big? And you're saying that when you compiled with the old toolchain, it was smaller? Well, for me it is bigger by more than a kilobyte. eosio-cpp compiled version is almost 21kB, whereas eosiocpp version is more than 22kB.

**Comment by sim31** [comment]
Thanks. Arch linux is rolling release, so I'm not sure what to answer to this question. [hello.wasm - compiled with eosio-cpp](https://drive.google.com/file/d/1bp6DVkt2_xJ20Rv_CmQVSGNBO5EP9CRd/view?usp=sharing). 
[hello1.wasm - compiled with eosiocpp](https://drive.google.com/open?id=1xIK9mvYTACftEJcUif5Xb3t27WVZhRxO)
