### ISSUE TITLE
inline action sender transfer failed with const char * type of memo

### ISSUE THREAD

**Issue by spartucus** [EOSIO/eosio.wasmsdk#60]
It's a duplication of https://github.com/EOSIO/eos/issues/4394.

When `memo` is `const char *`, it fails.
```
action(
	permission_level{_self,N(active)},
	N(eosio.token),N(transfer),
	std::make_tuple(_self,which->player,price,"payment from buyer")
).send();
```
while `memo` is `string`, it succeed.
```
action(
	permission_level{_self,N(active)},
	N(eosio.token),N(transfer),
	std::make_tuple(_self,which->player,price,std::string("payment from buyer"))
).send();
```

**Comment by larryk85** [comment]
@spartucus This is not a bug, it is a limitation of make_tuple.  The types const char* and std::string are not the same, so make_tuple will treat the const char* as a pointer, and the type of the memo field is an std::string, so explicit construction of std::string is needed to make std::make_tuple do the right thing.  Since, I foresee a lot of people stumbling on this one, I will post an issue for a wrapper over make_tuple that will handle the explicit conversion of const char*.

**Comment by spartucus** [comment]
👍
